// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNtpGXqozGLGFHrRNNtxNuojdMX23t5H8',
    appId: '1:325478952955:web:bcec0c507deba56130a55e',
    messagingSenderId: '325478952955',
    projectId: 'mobileapp-27621',
    authDomain: 'mobileapp-27621.firebaseapp.com',
    storageBucket: 'mobileapp-27621.appspot.com',
    measurementId: 'G-9PRY8G6J03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOtHR-L81W2SpJQlojTfwa349tzKrXG8',
    appId: '1:325478952955:android:ba975de467a3521830a55e',
    messagingSenderId: '325478952955',
    projectId: 'mobileapp-27621',
    storageBucket: 'mobileapp-27621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZPdu_zuiTThg6WPFhravdedKw_cYlPrw',
    appId: '1:325478952955:ios:36596e37f2532ac630a55e',
    messagingSenderId: '325478952955',
    projectId: 'mobileapp-27621',
    storageBucket: 'mobileapp-27621.appspot.com',
    androidClientId: '325478952955-lbc5kbig09vgl0igaee73fdadtde5bn4.apps.googleusercontent.com',
    iosClientId: '325478952955-51vkbg9bd0g2ouitnn20hpr0o4kqkptm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZPdu_zuiTThg6WPFhravdedKw_cYlPrw',
    appId: '1:325478952955:ios:a5b419b012bac30530a55e',
    messagingSenderId: '325478952955',
    projectId: 'mobileapp-27621',
    storageBucket: 'mobileapp-27621.appspot.com',
    androidClientId: '325478952955-lbc5kbig09vgl0igaee73fdadtde5bn4.apps.googleusercontent.com',
    iosClientId: '325478952955-u9db0c4ng29as66g33vme8s9m44qtrhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
